config/routes.rb
Slimeintheicemachine::Application.routes.draw do
  resources :facilities

end

app/models/facility.rb
require 'geocoder'

class Facility < ActiveRecord::Base
  acts_as_mappable :default_units   => :miles,
                   :default_formula => :flat,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  include Geocoder

  acts_as_gmappable :lat => "lat", :lng => "lng"

  def gmaps4rails_address
  # describe how to retrieve the address from your model, if you use directly a db column,
  # you can dry your code, see wiki
    "#{self.street_address} #{self.street_name}, #{self.city}, #{self.country}"
  end

  scope :not_geocoded, -> {where(lat: nil).where(lng: nil)}

  def self.add_geocodes
    Facility.not_geocoded.each {|f| f.add_geocode}
  end

  def add_geocode
    begin
      address = "#{street_address} #{street_name} #{city} #{state} #{zip}"
      coords = geocode(address)
      update_attributes(lat: coords[0], lng: coords[1])
    rescue Exception => e
      logger.error("Error geocoding address #{address} for facility #{name} (#{id}): #{e.message}")
    end
  end
end

# == Schema Information
#
# Table name: facilities
#
#  id             :integer          not null, primary key
#  account_id     :integer
#  name           :string(255)
#  street_address :string(255)
#  street_name    :string(255)
#  city           :string(255)
#  state          :string(255)
#  zip            :integer
#  phone          :string(255)
#  permit_type    :string(255)
#  expiration     :datetime
#  facility_type  :string(255)
#  district       :string(255)
#  risk           :string(255)
#  employees      :string(255)
#  score          :integer
#  inspected_on   :datetime
#  activity_type  :string(255)
#  inspector_id   :string(255)
#  inspector_name :string(255)
#  no_sites       :integer
#  lat            :float
#  lng            :float
#

app/models/violation.rb
class Violation < ActiveRecord::Base
end

# == Schema Information
#
# Table name: violations
#
#  id                 :integer          not null, primary key
#  facility_id        :integer
#  name               :string(255)
#  risk               :string(255)
#  address            :string(255)
#  facility_type      :string(255)
#  inspected_on       :datetime
#  inspector          :string(255)
#  site_type          :string(255)
#  violation_code     :string(255)
#  violation_weight   :integer
#  violation_comments :string(255)
#  correct_by_date    :datetime
#  score              :integer
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.limit(10)
    @json = Facility.limit(10).to_gmaps4rails
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render action: 'show', status: :created, location: @facility }
      else
        format.html { render action: 'new' }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params[:facility]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<%= form_for(@facility) do |f| %>
  <% if @facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% @facility.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb

<div class="container-fluid">
  <div class="row-fluid">
   <div class="navbar navbar-inverse navbar-float-top">
     <div class="navbar-inner">
	   <div class="container">
	   <a class="brand" href="#">Slime in the Ice Machine</a>
	   </div>
	 </div>
	</div>
      <div class="container span12">
	    <div class="span12">Input one of the fields below or navigate map to find most recent food inspection score and any violations given for your favorite Houston restaurants.</div>
        <div class="row-fluid">
          <div id="sidebar" class="span5">
		  <form class="form-horizontal">
		   <div class="control-group">
		   <label class="control-label" for="">Restuarant Name</label>
		     <div class="controls"><input type="text" class="input-medium search-query">
		      <button type="submit" class="btn">Search</button></div>
		   </div>
		   <div class="control-group">
		   <label class="control-label" for="">Address</label>
		     <div class="controls"><input type="text" class="input-medium search-query">
		      <button type="submit" class="btn">Search</button></div>
		   </div>
          </form>
          </div>
          <div id="map" class="span7">map</div>
        </div>
      </div>
   </div>



<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

  <%= @json %>

  <%= gmaps4rails(@json) %>

    <% @facilities.each do |facility| %>
      <tr>
        <td><%= facility.id %></td>
        <td><%= facility.name %></td>
        <td><%= link_to 'Show', facility %></td>
        <td><%= link_to 'Edit', edit_facility_path(facility) %></td>
        <td><%= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facility', new_facility_path %>

   <div class="footer"></div>
</div>


app/views/facilities/new.html.erb
<h1>New facility</h1>

<%= render 'form' %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>slime in the ice machine</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= yield :scripts %>
</body>
</html>